export enum ERole {
  GUEST = 'GUEST',
  EDITOR = 'EDITOR',
  ADMINISTRATOR = 'ADMINISTRATOR',
}

export const CODE_ROLE = ['GUEST', 'EDITOR', 'ADMINISTRATOR'];

export enum ACCESS {
  // User Module
  CREATE_USER = 'CREATE_USER',
  LIST_USERS = 'LIST_USERS',
  VIEW_USER = 'VIEW_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Deleted User
  LIST_DELETED_USER = 'LIST_DELETED_USER',
  VIEW_DELETED_USER = 'VIEW_DELETED_USER',
  RESTORE_USER = 'RESTORE_USER',

  // Role Module
  LIST_ROLES = 'LIST_ROLES',
  LIST_PERMISSION = 'LIST_PERMISSION',
  CREATE_ROLE = 'CREATE_ROLE',
  VIEW_ROLE = 'VIEW_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Media Module
  CREATE_MEDIA = 'CREATE_MEDIA',
  LIST_MEDIAS = 'LIST_MEDIAS',
  VIEW_MEDIA = 'VIEW_MEDIA',
  UPDATE_MEDIA = 'UPDATE_MEDIA',
  DELETE_MEDIA = 'DELETE_MEDIA',

  // Taxonomy module
  CREATE_TAXONOMY = 'CREATE_TAXONOMY',
  LIST_TAXONOMY = 'LIST_TAXONOMY',
  VIEW_TAXONOMY = 'VIEW_TAXONOMY',
  UPDATE_TAXONOMY = 'UPDATE_TAXONOMY',
  DELETE_TAXONOMY = 'DELETE_TAXONOMY',

  // Post module
  CREATE_POST = 'CREATE_POST',
  LIST_POST = 'LIST_POST',
  VIEW_POST = 'VIEW_POST',
  UPDATE_POST = 'UPDATE_POST',
  DELETE_POST = 'DELETE_POST',

  // Film module
  CREATE_FILM = 'CREATE_FILM',
  LIST_FILM = 'LIST_FILM',
  VIEW_FILM = 'VIEW_FILM',
  UPDATE_FILM = 'UPDATE_FILM',
  DELETE_FILM = 'DELETE_FILM',

  // Room module
  CREATE_ROOM = 'CREATE_ROOM',
  LIST_ROOM = 'LIST_ROOM',
  VIEW_ROOM = 'VIEW_ROOM',
  UPDATE_ROOM = 'UPDATE_ROOM',
  DELETE_ROOM = 'DELETE_ROOM',

  // Showtime module
  CREATE_SHOWTIME = 'CREATE_SHOWTIME',
  LIST_SHOWTIME = 'LIST_SHOWTIME',
  VIEW_SHOWTIME = 'VIEW_SHOWTIME',
  UPDATE_SHOWTIME = 'UPDATE_SHOWTIME',
  DELETE_SHOWTIME = 'DELETE_SHOWTIME',

  // Showtime module
  LIST_ORDER = 'LIST_ORDER',
  VIEW_ORDER = 'VIEW_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  // Option module
  CREATE_UPDATE_OPTION = 'CREATE_UPDATE_OPTION',
  LIST_OPTION = 'LIST_OPTION',
  DELETE_OPTION = 'DELETE_OPTION',
}

export const permissions = [
  {
    group: 'USER',
    permissions: [
      ACCESS.CREATE_USER,
      ACCESS.DELETE_USER,
      ACCESS.VIEW_USER,
      ACCESS.UPDATE_USER,
      ACCESS.LIST_USERS,
      ACCESS.LIST_DELETED_USER,
      ACCESS.VIEW_DELETED_USER,
      ACCESS.RESTORE_USER,
      ACCESS.LIST_PERMISSION,
    ],
  },
  {
    group: 'ROLE',
    permissions: [
      ACCESS.CREATE_ROLE,
      ACCESS.VIEW_ROLE,
      ACCESS.UPDATE_ROLE,
      ACCESS.DELETE_ROLE,
      ACCESS.LIST_ROLES,
    ],
  },
  {
    group: 'MEDIA',
    permissions: [
      ACCESS.CREATE_MEDIA,
      ACCESS.VIEW_MEDIA,
      ACCESS.UPDATE_MEDIA,
      ACCESS.DELETE_MEDIA,
      ACCESS.LIST_MEDIAS,
    ],
  },
  {
    group: 'TAXONOMY',
    permissions: [
      ACCESS.CREATE_TAXONOMY,
      ACCESS.VIEW_TAXONOMY,
      ACCESS.UPDATE_TAXONOMY,
      ACCESS.DELETE_TAXONOMY,
      ACCESS.LIST_TAXONOMY,
    ],
  },
  {
    group: 'POST',
    permissions: [
      ACCESS.CREATE_POST,
      ACCESS.VIEW_POST,
      ACCESS.UPDATE_POST,
      ACCESS.DELETE_POST,
      ACCESS.LIST_POST,
    ],
  },
  {
    group: 'FILM',
    permissions: [
      ACCESS.CREATE_FILM,
      ACCESS.VIEW_FILM,
      ACCESS.UPDATE_FILM,
      ACCESS.DELETE_FILM,
      ACCESS.LIST_FILM,
    ],
  },
  {
    group: 'ROOM',
    permissions: [
      ACCESS.CREATE_ROOM,
      ACCESS.VIEW_ROOM,
      ACCESS.UPDATE_ROOM,
      ACCESS.DELETE_ROOM,
      ACCESS.LIST_ROOM,
    ],
  },
  {
    group: 'SHOWTIME',
    permissions: [
      ACCESS.CREATE_SHOWTIME,
      ACCESS.VIEW_SHOWTIME,
      ACCESS.UPDATE_SHOWTIME,
      ACCESS.DELETE_SHOWTIME,
      ACCESS.LIST_SHOWTIME,
    ],
  },
  {
    group: 'ORDER',
    permissions: [
      ACCESS.VIEW_ORDER,
      ACCESS.UPDATE_ORDER,
      ACCESS.DELETE_ORDER,
      ACCESS.LIST_ORDER,
    ],
  },
  {
    group: 'OPTION',
    permissions: [
      ACCESS.CREATE_UPDATE_OPTION,
      ACCESS.DELETE_OPTION,
      ACCESS.LIST_OPTION,
    ],
  },
];
